### PR TITLE
Create HiP-Auth-v2.sln.DotSettings

### PR DESCRIPTION
**Pull request by janis-kra**

### CODE REVIEW

**Comment by janis-kra** [comment]
(╯°□°）╯︵ ┻━┻

**Comment by janis-kra** [comment]
Two issues here:

1. The Resharper config that the TFS applies seems to be different from that which my local machine applies
2. There are two errors that I have no idea how to fix, and I could not find the name of the rule that the error corresponds to (see below)

AuthWithIdentity\Services\AspNetIdentityProfileService.cs (53, 1)
AuthWithIdentity\Services\AspNetIdentityProfileService.cs(53,1): error : R# Cannot convert instance argument type 'System.Security.Principal.IPrincipal [System.Security.Principal, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a]' to 'System.Security.Principal.IPrincipal [System.Private.CoreLib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e]'

**Comment by SvenEV** [comment]
Congrats, you have found another [bug in Resharper](https://stackoverflow.com/questions/44520318/resharper-error-cannot-convert-instance-argument-type-system-security-principa)! I'm not sure whether specific errors can be disabled in Resharper. To workaround the issue, I have excluded the corresponding file from inspection.

**Comment by SvenEV** [comment]
Ok, finally I got it to work. There was one issue remaining with the "::" syntax in CSS not being compatible to IE8, so I raised the compatibility level to IE10 (as part of the DotSettings file). But somehow, this setting does not seem to be honored by ReSharper in our TFS build definition (maybe we have a different version in TFS?). So I added additional "ReSharper disable..."-comments.

**Review by SvenEV — APPROVED** [review]

**Pull request merged**
